name: NuGetCD

on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:

  prepare:
    name: FetchAndTag
    runs-on: windows-latest
    env:
      Test_Project_File: \test\ServiceFabric.Mocks.NetCoreTests\ServiceFabric.Mocks.NetCoreTests.csproj
    steps:
    - uses: actions/checkout@v3

    # create version
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dry_run: false

    # install dotnet 6
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    # Create SNK 
    - name: Create SNK
      shell: pwsh
      run: |
        .\ExtractPrivateKey.ps1 "${{ secrets.Pfx_Key }}"

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test --logger "trx;LogFileName=results.trx" ${Test_Project_File}

    # Run dotnet release build
    - name: Run build
      run: dotnet pack --configuration RELEASE -p:PackageVersion=${{ steps.tag_version.outputs.new_version }} -o .

    # create GH release
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}

    # publish nuget package artifact
    - name: Upload Package for Publishing
      uses: actions/upload-artifact@v3
      with:
        name: PackedLib
        path: ./ServiceFabric.Mocks.${{ steps.tag_version.outputs.new_version }}.nupkg

    # publish GH nuget package artifact
    - name: Push Package to GitHub
      run: dotnet nuget push --api-key ${{secrets.GITHUB_TOKEN}} --source "https://nuget.pkg.github.com/loekd/index.json" ServiceFabric.Mocks.${{ steps.tag_version.outputs.new_version }}.nupkg

    # publish packge to nuget
    - name: Push Package to GitHub
      run: dotnet nuget push --api-key ${{secrets.NUGETPUSH}} --source "https://api.nuget.org/v3/index.json" ServiceFabric.Mocks.${{ steps.tag_version.outputs.new_version }}.nupkg

    
